// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD__V5AXSxBWxWltTyCeW_q_OvaEpPw5Os',
    appId: '1:652326584866:web:f83e4deb5ddb676dbf007b',
    messagingSenderId: '652326584866',
    projectId: 'my-auth-b0dc2',
    authDomain: 'my-auth-b0dc2.firebaseapp.com',
    databaseURL: 'https://my-auth-b0dc2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-auth-b0dc2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQsUi9mnoWiiyApSZIliyzz0PgIJ04kGA',
    appId: '1:652326584866:android:f09c7e2d0f43d449bf007b',
    messagingSenderId: '652326584866',
    projectId: 'my-auth-b0dc2',
    databaseURL: 'https://my-auth-b0dc2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-auth-b0dc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXHg9p_Qqc-7zJMeoF830ea9X_pMHQEFI',
    appId: '1:652326584866:ios:9e73bc444eee6749bf007b',
    messagingSenderId: '652326584866',
    projectId: 'my-auth-b0dc2',
    databaseURL: 'https://my-auth-b0dc2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-auth-b0dc2.appspot.com',
    iosBundleId: 'com.example.receipnesia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXHg9p_Qqc-7zJMeoF830ea9X_pMHQEFI',
    appId: '1:652326584866:ios:2f364bf104242ccdbf007b',
    messagingSenderId: '652326584866',
    projectId: 'my-auth-b0dc2',
    databaseURL: 'https://my-auth-b0dc2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-auth-b0dc2.appspot.com',
    iosBundleId: 'com.example.receipnesia.RunnerTests',
  );
}
